---
  - name: Localhosts Tasks 
    hosts: local
    connection: local
    gather_facts: True
  
    tasks:
      - name: Delete ~/.ssh/known_hosts file
        ignore_errors: yes
        file:
          state: absent
          path: ~/.ssh/known_hosts
   
    

