---
  - name: Hetzner Tasks on Master
    hosts: master
    remote_user: root
    tasks:
      - name: Install CNI in Kubernetes
        shell: 
          cmd: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

  - name:  Copy on Master
    hosts: master
    remote_user: root
    tasks: 
      - name: Copy current cni.kubeconfig file from master to local
        synchronize:  src={{ item }} dest=./files/ mode=pull
        with_items: 
          - /root/cni.kubeconfig

  - name: Copy on Worker
    hosts: worker
    remote_user: root
    tasks: 
      - name: Copy the file from local to workers
        copy: 
            src: files/cni.kubeconfig 
            dest: /root/
            force: yes
